"""create extract_mogi table

Revision ID: 8c439dc4dee0
Revises: b5466a6c2b03
Create Date: 2026-01-26 15:19:28.962918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c439dc4dee0'
down_revision: Union[str, Sequence[str], None] = 'b5466a6c2b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extract_mogi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_empresa', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('celular_whatsapp', sa.String(), nullable=True),
    sa.Column('facebook_link', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('data_extracao', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extract_mogi')
    # ### end Alembic commands ###
